name: Update translations

on:
    schedule:
        - cron:  '*/5 * * * *'

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                python-version: 3.7
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install transifex
                  tx pull -a --mode reviewed
